# version: "3.8"

# services:
#   app: 
#     build: .
#     ports:
#       - "8090:8080"
#     networks:
#       - anvil-network
  
#   postgres:
#     image: postgres:latest
#     environment:
#      POSTGRES-USER:
#      POSTGRES-PASSWORD:
#      POSTGRES-DB: 
#     ports: 
#       5432:5433
#     networks:
#       - anvil-network
#     volumes:
#       - anvil-data:/var/lib/postgresql/data
  
#   networks:
#     anvil-network:
#       driver: bridge

  
#   volumes:
#     anvil-data: