services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: exercisedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cheeku@2004
    ports:
      - "5432:5432"
    volumes:
      - anvil_data:/var/lib/postgresql/data

  app:
    image: anvil1:latest
    container_name: anvil_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exercisedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cheeku@2004
    ports:
      - "8080:8080"

volumes:
  anvil_data:
